version: "3.9"

services:
  blog-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postegresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  blog-platform:
    build: .
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${SERVER_PORT}"
    volumes:
      - .:/blog-platform
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
    depends_on:
      - blog-db