# Generated by Django 4.2.11 on 2024-04-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_id_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
